// =============================================================================
// BiomeData — catalogo dati dei 7 biomi. Riusa il tipo BiomeId gia'
// esistente nel progetto (types.ts), non lo ridefinisce. Ogni bioma e'
// completamente autonomo e configurabile: nessun valore e' hardcoded nel
// BiomeManager o nell'EnemySpawnManager, tutto vive qui.
import type { BiomeDefinition, BiomeId } from "./types";

const RES = (id: string, name: string) => ({ id, name });

export const BIOME_DEFINITIONS: Record<BiomeId, BiomeDefinition> = {
  prateria: {
    id: "prateria",
    name: "Prateria",
    minLevel: 1,
    maxLevel: 5,
    minimapColor: "#7bc44c",
    music: "prateria_theme.mp3",
    environment: "Erba alta e colline dolci intorno al Villaggio.",
    commonEnemyIds: [
      "slime_verde",
      "lupo",
      "cinghiale",
      "ape_gigante",
      "goblin_guerriero",
      "goblin_arciere",
      "goblin_sciamano",
    ],
    eliteEnemyIds: ["alpha_wolf", "goblin_capitano"],
    bossEnemyId: "goblin_re",
    resources: [RES("legno", "Legno"), RES("erbe", "Erbe"), RES("pietra", "Pietra")],
    spawn: {
      maxEnemies: 6,
      spawnChancePerTick: 0.6,
      respawnTimeSec: 4.5,
      minDistanceFromPlayer: 3,
      minDistanceBetweenEnemies: 2,
      eliteChance: 0.05,
    },
  },
  foresta: {
    id: "foresta",
    name: "Foresta",
    minLevel: 4,
    maxLevel: 9,
    minimapColor: "#2f7a3a",
    music: "foresta_theme.mp3",
    environment: "Bosco fitto e ombroso, luce che filtra a stento dalle chiome.",
    commonEnemyIds: ["ragno_gigante", "ent_giovane", "orso", "treant", "fata_oscura"],
    eliteEnemyIds: ["dire_bear", "ancient_treant"],
    bossEnemyId: "re_della_foresta",
    resources: [RES("legno_antico", "Legno Antico"), RES("funghi", "Funghi"), RES("erbe_rare", "Erbe Rare")],
    spawn: {
      maxEnemies: 6,
      spawnChancePerTick: 0.55,
      respawnTimeSec: 5,
      minDistanceFromPlayer: 3,
      minDistanceBetweenEnemies: 2,
      eliteChance: 0.045,
    },
  },
  deserto: {
    id: "deserto",
    name: "Deserto",
    minLevel: 8,
    maxLevel: 14,
    minimapColor: "#d9b25c",
    music: "deserto_theme.mp3",
    environment: "Dune infinite sotto un sole implacabile.",
    commonEnemyIds: ["scorpione", "scarabeo_deserto", "cobra", "bandito", "mummia"],
    eliteEnemyIds: ["scorpione_reale", "campione_bandito"],
    bossEnemyId: "re_scorpione",
    resources: [RES("cristalli", "Cristalli"), RES("sabbia_magica", "Sabbia Magica"), RES("ferro", "Ferro")],
    spawn: {
      maxEnemies: 6,
      spawnChancePerTick: 0.5,
      respawnTimeSec: 5.5,
      minDistanceFromPlayer: 3.5,
      minDistanceBetweenEnemies: 2.5,
      eliteChance: 0.04,
    },
  },
  palude: {
    id: "palude",
    name: "Palude",
    minLevel: 12,
    maxLevel: 18,
    minimapColor: "#4a6b4a",
    music: "palude_theme.mp3",
    environment: "Acque torbide, nebbia bassa e vegetazione marcescente.",
    commonEnemyIds: ["slime_tossico", "rana_gigante", "coccodrillo_selvatico", "zanzara_gigante", "serpente_palude"],
    eliteEnemyIds: ["crocodile_alpha", "hydra_hatchling"],
    bossEnemyId: "idra",
    resources: [RES("erbe_tossiche", "Erbe Tossiche"), RES("gelatine", "Gelatine"), RES("funghi_palude", "Funghi")],
    spawn: {
      maxEnemies: 6,
      spawnChancePerTick: 0.5,
      respawnTimeSec: 5.5,
      minDistanceFromPlayer: 3.5,
      minDistanceBetweenEnemies: 2.5,
      eliteChance: 0.04,
    },
  },
  montagne: {
    id: "montagne",
    name: "Montagna",
    minLevel: 16,
    maxLevel: 23,
    minimapColor: "#8a8a8f",
    music: "montagna_theme.mp3",
    environment: "Picchi rocciosi e sentieri stretti battuti dal vento.",
    commonEnemyIds: ["troll", "golem_montagna", "arpia", "aquila_gigante", "lupo_delle_nevi"],
    eliteEnemyIds: ["mountain_giant", "elder_harpy"],
    bossEnemyId: "re_dei_troll",
    resources: [RES("ferro_montagna", "Ferro"), RES("pietra_montagna", "Pietra"), RES("oro_montagna", "Oro")],
    spawn: {
      maxEnemies: 5,
      spawnChancePerTick: 0.45,
      respawnTimeSec: 6,
      minDistanceFromPlayer: 4,
      minDistanceBetweenEnemies: 3,
      eliteChance: 0.035,
    },
  },
  ghiacciaio: {
    id: "ghiacciaio",
    name: "Ghiacciaio",
    minLevel: 20,
    maxLevel: 28,
    minimapColor: "#bfe3f0",
    music: "ghiacciaio_theme.mp3",
    environment: "Distese di ghiaccio perenne e venti gelidi taglienti.",
    commonEnemyIds: ["golem_ghiaccio", "lupo_artico", "yeti", "spirito_del_gelo", "pinguino_guerriero"],
    eliteEnemyIds: ["frost_yeti", "ice_guardian"],
    bossEnemyId: "re_del_gelo",
    resources: [
      RES("cristalli_ghiaccio", "Cristalli di Ghiaccio"),
      RES("minerali", "Minerali"),
      RES("erbe_rare_ghiaccio", "Erbe Rare"),
    ],
    spawn: {
      maxEnemies: 5,
      spawnChancePerTick: 0.45,
      respawnTimeSec: 6,
      minDistanceFromPlayer: 4,
      minDistanceBetweenEnemies: 3,
      eliteChance: 0.035,
    },
  },
  vulcano: {
    id: "vulcano",
    name: "Vulcano",
    minLevel: 25,
    maxLevel: 35,
    minimapColor: "#c9432a",
    music: "vulcano_theme.mp3",
    environment: "Colate di lava e cenere calda sospesa nell'aria.",
    commonEnemyIds: ["slime_lava", "salamandra", "elementale_fuoco", "demone_minore", "drago_cucciolo"],
    eliteEnemyIds: ["fire_giant", "infernal_demon"],
    bossEnemyId: "drago_antico",
    resources: [RES("lava_crystal", "Lava Crystal"), RES("zolfo", "Zolfo"), RES("mithril", "Mithril")],
    spawn: {
      maxEnemies: 5,
      spawnChancePerTick: 0.4,
      respawnTimeSec: 6.5,
      minDistanceFromPlayer: 4,
      minDistanceBetweenEnemies: 3,
      eliteChance: 0.03,
    },
  },
};

export function getBiomeDefinition(id: BiomeId): BiomeDefinition {
  return BIOME_DEFINITIONS[id];
}
